### ISSUE TITLE
Having trouble boot into system.

### ISSUE THREAD

**Issue by mlch911** [stevannetto/EFI-ASROCK-Z690M-ITX-AX#1]
Have you tried this board with old GPU?
I'm using rx580. And I can't see any display until boot into OS. I can boot into Windows.
I can only see the boot screen, config bios and see the opencore boot screen via iGPU.
I know I can't use iGPU to boot opencore. But I can't see any display while boot opencore with rx580.
Any ideas ?

**Comment by mlch911** [comment]
It's the GPU not fully support UEFI Boot. I switch it to 6800 and all works fine.

**Comment by stevannetto** [comment]
Hi,
Sorry for the late reply. I believe RX580 would work with either the following tweaks:
By removing agdpmod=pikera under config.plist.
By replacing agdpmod=pikera with igfxonln=1, again under config.plist.
I glad to hear you got it working with the RX6800.

**Comment by mlch911** [comment]
> Hi,
> 
> Sorry for the late reply. I believe RX580 would work with either the following tweaks:
> 
> By removing agdpmod=pikera under config.plist.
> 
> By replacing agdpmod=pikera with igfxonln=1, again under config.plist.
> 
> I glad to hear you got it working with the RX6800.

I can't boot now with rx6800🤣. You can see the other issue.
